### 1.1 Создание вектора

In [5]:
import numpy as np

In [7]:
vector_rw = np.array([1,2,3])
vector_column = np.array([[1],
                         [2],
                         [3]])
vector_rw, vector_column

(array([1, 2, 3]),
 array([[1],
        [2],
        [3]]))

### 1.2 Создание матрицы

In [9]:
# Способ 1
matrix = np.array([[1,2],
                 [1,2],
                 [1,2]])
matrix

# Способ 2
matrix_object = np.mat([[1,2],
                         [1,2],
                         [1,2]])

type(matrix), type(matrix_object)

(numpy.ndarray, numpy.matrix)

### 1.3 Создание разреженной матрицы

In [12]:
from scipy import sparse
sparse_matrix = np.array([[0,0],
                          [0,1],
                          [3,0],])
csr_matrix = sparse.csr_matrix(sparse_matrix)
print(csr_matrix)

  (1, 1)	1
  (2, 0)	3


In [16]:
matrix_large = np.array([[0,0,0,0,0,0,0,0,0,0],
                        [0,0,0,0,0,5,0,0,0,0],
                        [2,0,0,0,0,0,0,0,6,0],])
matrix_large_csr = sparse.csc_matrix(matrix_large)
print(matrix_large_csr)

  (2, 0)	2
  (1, 5)	5
  (2, 8)	6


### 1.4 Предварительноe распределение массивов в Numpy (np.zeros) (np.full(shape,fill_value))

In [20]:
vector = np.zeros(shape=5)
matrix = np.full(shape=(3,3), fill_value=2)
vector, matrix

(array([0., 0., 0., 0., 0.]),
 array([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]))

### 1.5 Обращение к элементу массива

In [23]:
vector = np.array([1,2,3,4,5,6,7,8,9,10])
matrix = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],])
matrix[1,1]

6

In [25]:
vector[1::2]
matrix[1:,:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### 1.6 Описание матрицы 

In [28]:
#shape 
matrix.shape, matrix.size, matrix.ndim

((3, 4), 12, 2)

### 1.7 Использование функции для каждого элемента

In [31]:
add_100 = lambda x: x + 100

vectorized_add_100 = np.vectorize(add_100)
vectorized_add_100(matrix)

# метод транслирование
matrix + 10

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])

## 1.8 Поиск наибольших и наименьших значени

In [34]:
np.max(matrix), np.min(matrix)
print(np.max(matrix,axis=1))
print(np.max(matrix,axis=0))

[ 4  8 12]
[ 9 10 11 12]


### 1.9 Вычиление среднего значения, дисперсии и стандартного отклонения

In [37]:
norm_matrix = np.array([[1,1,1]])
mean = np.mean(norm_matrix)
dis = np.var(norm_matrix)
std = np.std(norm_matrix)
print(f'Mean: {mean}')
print(f'Mean: {dis}')
print(f'Mean: {std}')

Mean: 1.0
Mean: 0.0
Mean: 0.0


### 1.10 Изменение формы массива

In [40]:
reshaped_matrix = matrix.reshape(6,2)
reshaped_matrix

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [42]:
reshaped_matrix = matrix.reshape(1,-1)
reshaped_matrix

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

### 1.11 Транспонирование вектора и матрицы

In [51]:
print(matrix)
print(matrix.T)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [69]:
np.array([[1,2,3,4,5]]).T

array([[1],
       [2],
       [3],
       [4],
       [5]])

### 1.12 Преобразование матрицы в одномерный вектор

In [96]:
print(matrix.flatten().shape)
print(matrix.reshape(1,-1).shape)

(12,)
(1, 12)


In [106]:
# ravel for list of matrix
matrix_a = np.array([[1,2],
                    [3,4]])
matrix_b = np.array([[5,6],
                    [7,8]])
matrix_list = [matrix_a, matrix_b]
np.ravel(matrix_list)

array([1, 2, 3, 4, 5, 6, 7, 8])

### 1.13 Определение ранга матрицы

In [109]:
np.linalg.matrix_rank(matrix)

2

### 1.14 Вывод диагонали матрицы 

In [122]:
print(matrix)
# главный диагональ
print(matrix.diagonal())
# побочный диагональ
print(matrix.diagonal(offset=1))
print(matrix.diagonal(offset=-1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  6 11]
[ 2  7 12]
[ 5 10]


### 1.16 Вычисление скалярного произведения 

In [131]:
np.dot(matrix_a,matrix_b)
matrix_a @ matrix_b

array([[19, 22],
       [43, 50]])

### 1.20 Генерация псевдослуайных значений 

In [168]:
# Сгенерировамь мри случайных дробных числа в диапазоне ом 0.0 до 1.0 
np.random.seed(0)
np.random.random(10)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [332]:
# Сгенерировамь мри случайных целых в диапазоне ом 0 до 10 
ran2=np.random.randint(0,11,5)
print(ran2.std())

2.6381811916545836


In [330]:
# Получимь мри числа нормального распределения со средним значением 0.0 
# и смандармным омклонением 1.0 
ran = np.random.normal(0.0, 1.0, 3) 
print(ran.std())

1.04816271830125


In [380]:
# Получимь три числа, коморые будум бoльшe или равны 1.0 и меньше 2.0
np.random.uniform(1.0, 3.0, 3) 

array([1.9529544 , 1.97586914, 1.9170291 ])