### 1.1 Создание вектора

In [3]:
import numpy as np

In [19]:
vector_rw = np.array([1,2,3])
vector_column = np.array([[1],
                         [2],
                         [3]])
vector_rw, vector_column

(array([1, 2, 3]),
 array([[1],
        [2],
        [3]]))

### 1.2 Создание матрицы

In [39]:
# Способ 1
matrix = np.array([[1,2],
                 [1,2],
                 [1,2]])
matrix

# Способ 2
matrix_object = np.mat([[1,2],
                         [1,2],
                         [1,2]])

type(matrix), type(matrix_object)

(numpy.ndarray, numpy.matrix)

### 1.3 Создание разреженной матрицы

In [50]:
from scipy import sparse
sparse_matrix = np.array([[0,0],
                          [0,1],
                          [3,0],])
csr_matrix = sparse.csr_matrix(sparse_matrix)
print(csr_matrix)

  (1, 1)	1
  (2, 0)	3


In [86]:
matrix_large = np.array([[0,0,0,0,0,0,0,0,0,0],
                        [0,0,0,0,0,5,0,0,0,0],
                        [2,0,0,0,0,0,0,0,6,0],])
matrix_large_csr = sparse.csc_matrix(matrix_large)
print(matrix_large_csr)

  (2, 0)	2
  (1, 5)	5
  (2, 8)	6


### 1.4 Предварительноe распределение массивов в Numpy (np.zeros) (np.full(shape,fill_value))

In [99]:
vector = np.zeros(shape=5)
matrix = np.full(shape=(3,3), fill_value=2)
vector, matrix

(array([0., 0., 0., 0., 0.]),
 array([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]))

### 1.5 Обращение к элементу массива

In [220]:
vector = np.array([1,2,3,4,5,6,7,8,9,10])
matrix = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],])
matrix[1,1]

6

In [218]:
vector[1::2]
matrix[1:,:]

array([[ 4,  5,  6,  8],
       [ 7,  8,  9, 10]])

### 1.6 Описание матрицы 

In [144]:
#shape 
matrix.shape, matrix.size, matrix.ndim

((3, 3), 9, 2)

### 1.7 Использование функции для каждого элемента

In [157]:
add_100 = lambda x: x + 100

vectorized_add_100 = np.vectorize(add_100)
vectorized_add_100(matrix)

# метод транслирование
matrix + 10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

## 1.8 Поиск наибольших и наименьших значени

In [185]:
np.max(matrix), np.min(matrix)
print(np.max(matrix,axis=1))
print(np.max(matrix,axis=0))

[3 6 9]
[7 8 9]


### 1.9 Вычиление среднего значения, дисперсии и стандартного отклонения

In [207]:
norm_matrix = np.array([[1,1,1]])
mean = np.mean(norm_matrix)
dis = np.var(norm_matrix)
std = np.std(norm_matrix)
print(f'Mean: {mean}')
print(f'Mean: {dis}')
print(f'Mean: {std}')

Mean: 1.0
Mean: 0.0
Mean: 0.0


### 1.10 Изменение формы массива

In [234]:
reshaped_matrix = matrix.reshape(6,2)
reshaped_matrix

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [246]:
reshaped_matrix = matrix.reshape(1,-1)
reshaped_matrix

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])